-keepattributes *Annotation*, InnerClasses
-dontwarn org.jacobrakaifoundation.beanstalk.**
-keep class org.jacobrakaifoundation.beanstalk.** { *; }
-keepclassmembers class org.jacobrakaifoundation.beanstalk.** { *; }
